# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20160730_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Church',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
