# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 00:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zip', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('county', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('area_code', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zipcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=20, null=True)),
                ('address1', models.CharField(max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('x_lat', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('y_long', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('pastor', models.CharField(max_length=50, null=True)),
                ('pastor_number', models.CharField(max_length=20, null=True)),
                ('church_area1', models.CharField(blank=True, max_length=50, null=True)),
                ('church_area2', models.CharField(blank=True, max_length=50, null=True)),
                ('other_language', models.CharField(blank=True, max_length=50, null=True)),
                ('approval', models.PositiveSmallIntegerField(choices=[(0, 'Unapproved'), (1, 'Approved')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(null=True)),
                ('end', models.TimeField(null=True)),
                ('students', models.PositiveIntegerField(null=True)),
                ('day', models.PositiveSmallIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Help_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Help')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('korean', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='Min_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('korean', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Min_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address1', models.CharField(max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('church_name', models.CharField(max_length=50, null=True)),
                ('church_contact', models.CharField(max_length=50, null=True)),
                ('church_phone', models.CharField(max_length=20, null=True)),
                ('approval', models.PositiveSmallIntegerField(choices=[(0, 'Unapproved'), (1, 'Approved')], default=0)),
                ('level', models.PositiveSmallIntegerField(default=5, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='min_category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Min_Group'),
        ),
        migrations.AddField(
            model_name='interest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Min_Category'),
        ),
        migrations.AddField(
            model_name='interest',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Volunteer'),
        ),
        migrations.AddField(
            model_name='help_request',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Volunteer'),
        ),
        migrations.AddField(
            model_name='help',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Min_Category'),
        ),
        migrations.AddField(
            model_name='help',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Church'),
        ),
        migrations.AddField(
            model_name='help',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Volunteer'),
        ),
    ]
