# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160804_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ministries',
        ),
    ]
